jobs:
  - job: register_model
    displayName: Register Model
    dependsOn: train_model

    variables:
      - template: ./variables.yml

    steps:
      - task: AzureCLI@2
        displayName: Install Azure ML CLI
        inputs:
          scriptType: bash
          azureSubscription: $(service_connection)
          scriptLocation: inlineScript
          inlineScript: az extension add -n azure-cli-ml

      - task: DownloadBuildArtifacts@0
        displayName: Download Run Metadata Artifact
        inputs:
          source: current
          artifactName: run-metadata
          downloadPath: $(Pipeline.Workspace)

      - task: AzureCLI@2
        displayName: Register Model
        inputs:
          scriptType: bash
          azureSubscription: $(service_connection)
          scriptLocation: inlineScript
          inlineScript: |
            az ml model register \
            --name $(project_name)-model \
            --asset-path outputs/model.pkl \
            --experiment-name $(project_name)-experiment \
            --output-metadata-file model.json \
            --workspace-name $(workspace_name) \
            --resource-group $(resource_group) \
            --run-metadata-file $(Pipeline.Workspace)/run-metadata/run.json

      - task: PublishBuildArtifacts@1
        displayName: Publish Model Metadata Artifact
        inputs:
          pathToPublish: $(System.DefaultWorkingDirectory)/model.json
          artifactName: model-metadata
